# Numpy - библиотека для работы с числовыми масивами

In [33]:
import numpy as np

In [34]:
a = [1,2,3,0,7,6,4,3]

In [35]:
np_a = np.array(a)

In [36]:
np_a

array([1, 2, 3, 0, 7, 6, 4, 3])

In [37]:
np_a.mean()

3.25

In [38]:
np_a.max()

7

In [39]:
np_a.min()

0

In [40]:
# размеры массива
np_a.shape

(8,)

In [41]:
np_b = np.array([[1,2,3],[4,5,6]])
np_b.shape

(2, 3)

In [42]:
np1 = np.zeros((3,2))
print(np1)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [43]:
# arange(x,y,z), где x - начало, y - конец, z - шаг

np2 = np.arange(1,10,2)
print(np2)

[1 3 5 7 9]


In [44]:
# linspace(x,y,z), где x - начало, y - конец, z - количество элементов/точек

np3 = np.linspace(1,10,3)
print(np3)

[ 1.   5.5 10. ]


In [45]:
np4 = np.arange(12)
print(np4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [46]:
# reshape(x,y), где x - строки, y - столбцы

np5 = np4.reshape(4,3)
print(np5)
print(np4)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [47]:
# математические операции

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print('a+b = ', a+b)
print('a-b = ', a-b)
print('sin(a) = ', np.sin(a))

a+b =  [ 6  8 10 12]
a-b =  [-4 -4 -4 -4]
sin(a) =  [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
